version: "3.9"

services:
  db:
    image: postgres
    container_name: db_challenge
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./backend/.env 

  web:
    build: .
    container_name: challenge
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/codeDjango
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    network_mode: host

  redis:
    image: redis:latest