# Generated by Django 4.2.5 on 2023-09-18 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('country', 'DateTime')},
        ),
        migrations.CreateModel(
            name='WeatherDataDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('Temperature_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Temperature_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Unit', models.CharField(max_length=10)),
                ('Day', models.CharField(max_length=250)),
                ('Night', models.CharField(max_length=250)),
                ('Country', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Country', 'DateTime')},
            },
        ),
    ]
