# Generated by Django 4.2.5 on 2023-09-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weatherdata_unique_together_weatherdataday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weatherdataday',
            unique_together=set(),
        ),
    ]
